services:
  app:
    build: .
    container_name: heart_checker_app
    ports:
      - "8000:8000"
    volumes:
      # ローカルのappディレクトリをコンテナの/appにマウントし、コード変更を即時反映
      - ./app:/app
      # ダウンロードしたデータを永続化
      - ./data:/app/data
    # GPUを使用する場合は以下のコメントを外す
    # ただし、DockerがNVIDIA GPUをサポートしている必要があります
    # 参考: https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/heart_db
    # dbサービスが起動してからappサービスを起動する
    depends_on:
      - db
    # コンテナ起動時に実行するコマンド
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  # ここでDBを定義
  db:
    image: postgres:15
    container_name: heart_checker_db
    volumes:
      # DBのデータを永続化
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=heart_db
    ports:
      - "5432:5432"

volumes:
  postgres_data: